### ISSUE TITLE
bin/hedgehog assumes chruby is installed 

### ISSUE THREAD

**Issue by samtgarson** [Dan2552/Hedgehog#6]
Running `bin/hedgehog` causes:

```
bin/hedgehog: line 7: /usr/local/share/chruby/chruby.sh: No such file or directory
bin/hedgehog: line 8: chruby: command not found
```

`bin/hedgehog` should probably somehow be agnostic to how you install ruby?

**Comment by Dan2552** [comment]
For the time being `bundle exec ruby app/app.rb` should work from any Ruby

Not yet sure what's best thing to do here. Perhaps something that just tries all the common methods like [here](https://github.com/Dan2552/gathering-of-scripts/blob/master/ruby/chruby-functions#L9-L23). Or maybe just remove the call altogether and rely on it being set before running.
